Home work1
Minrael/2020-1-Track-Frontend-M-Kerechanina pull request #1
Opened 2020-03-15 17:12 UTC by Minrael

# Домашнее задание №3

Прошу @martinkomitsky или @chexex  проверить его.

Что было сделано:
*Реализована виртуальная клавиатура emoji:
*При клике на смайл вставляется код
*При отправке код заменяется на картинку

2020-03-18 09:44 UTC, martinkomitsky requested changes
тревис не собирается из-за ошибок, которые надо поправить
https://travis-ci.org/github/Minrael/2020-1-Track-Frontend-M-Kerechanina/builds/663232499?utm_source=github_status&utm_medium=notification

2020-03-22 16:17 UTC, martinkomitsky requested changes
Исправить замечания:
1. Сделать относительные ссылки
2. Замечания в коде
3. Не работают спрайты
![image](https://user-images.githubusercontent.com/14847018/77254364-a7c48580-6c71-11ea-96ec-bad321d2f095.png)
Для этого надо донастроить сборку в webpack конфиге. https://www.npmjs.com/package/css-sprite-loader#config

Сейчас инструкция "?sprite" никак не обрабатывается

2020-03-22 16:17 UTC, martinkomitsky commented on src/App.js
> +          <Link to={`${process.env.PUBLIC_URL}/user/signin`}> Sign in </Link>
зачем тут указывать абсолютные ссылки `process.env.PUBLIC_URL`? относительной ссылки достаточно

2020-03-22 16:17 UTC, martinkomitsky commented on src/components/MessageList.js
> +                let withEmoji = msg.replace(/&#(\w+)#&/g, ' <i class="$1 + emoji"}></i> ');
Преобразуется в строчку:
```
<i class="crying + emoji" }=""></i>
```
Полагаю, что `+` там не нужен и `}` тоже

2020-03-22 17:12 UTC, Minrael commented on src/App.js
> +          <Link to={`${process.env.PUBLIC_URL}/user/signin`}> Sign in </Link>
В webpack.config строки 15, 320-323 указан плагин как в инструкции по ссылке, но спрайт действительно не собирается.

С относительными ссылками при сборке в тревисе по адресу homepage не открывается приложение

2020-03-22 17:29 UTC, martinkomitsky commented on config/webpackDevServer.config.js
> +  };
все, что тут происходит - полностью перезатирается строчкой 26. Нужно было не просто скопировать код из документации, а с умом подставить плагин туда, где он требуется

2020-03-22 17:32 UTC, martinkomitsky commented on src/App.js
> +          <Link to={`${process.env.PUBLIC_URL}/user/signin`}> Sign in </Link>
> С относительными ссылками при сборке в тревисе по адресу homepage не открывается приложение

a, базовая ошибка. Нужно выставить параметр basename;

https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/docs/api/BrowserRouter.md#basename-string

В зависимости от окружения (`process.env.NODE_ENV !== 'production'`), он должен либо устанавливаться в `2020-1-Track-Frontend-M-Kerechanina`, либо не устанавливаться.

2020-03-22 18:23 UTC, martinkomitsky commented on src/App.js
> +          <Link to={`${process.env.PUBLIC_URL}/user/signin`}> Sign in </Link>
https://github.com/track-mail-ru/2019-2-Track-Frontend-M-Komitsky/commit/7128d2417d369e5fd26be384bdb88e81d763788e вот, как надо было сделать конфиг

2020-03-25 17:00 UTC, chexex reviewed
Нужна сборка

2020-03-25 17:00 UTC, chexex commented on src/actions/getMessage.js
> +  //GET_MESSAGE_FAILURE,
Почему?

2020-03-25 17:00 UTC, chexex commented on src/actions/sendMessage.js
> +  //SEND_MESSAGE_FAILURE,
Почему?

2020-03-25 17:00 UTC, chexex commented on src/components/EmojiTool.js
> +}
Обратить внимание на возможности ES6

```js
const Emoji = ({name, handleClick}) => (
  <i className={`${name} emoji`} onClick={() => handleClick(name)} />
)

// ...

<Emoji name='smile' handleClick={props.handleEmojiClick} />
```

2020-03-25 17:00 UTC, chexex commented on src/components/FormInput.js
> +//import styles from '../styles/globalStyles.css'
Комментарии в коде должны дополнять код, но не скрывать. Здесь нужно либо вернуть строчку, либо удалить ее совсем

2020-03-25 17:00 UTC, chexex commented on src/components/FormInput.js
> +            {emojiView === true ? <EmojiTool handleEmojiClick = { handleEmojiClick }/>:<div></div>}
```js
{emojiView && <EmojiTool handleEmojiClick={handleEmojiClick} /> }
```

2020-03-25 17:00 UTC, chexex commented on src/components/FormInput.js
> +            </section>
Линтеры подключены?

2020-03-25 17:00 UTC, chexex commented on src/components/Header.js
> +}*/
Лишнее

2020-03-25 17:00 UTC, chexex commented on src/components/MessageList.js
> +    let i = 0;
i не нужен

2020-03-25 17:00 UTC, chexex commented on src/components/MessageList.js
> +        messages.forEach( function(msg) {
```js
messages && messages.forEach((msg, idx) => {
  // ...
}
```

2020-03-25 17:00 UTC, chexex commented on src/components/MessageList.js
> +                msgs_render.push(messageBox);
вместо 
```js
let container = [];

someArray.forEach(data => {container.push(process(data))});
```

лучше использовать 

```js
someArray.map(data => (process(data)));
```

2020-03-25 17:00 UTC, chexex commented on src/components/MessageList.js
> +                let withEmoji = msg.replace(/&#(\w+)#&/g, ' <i class="$1 emoji"></i> ');
Уточню, понятно ли тебе, что здесь написано?

- /g
- (\w+)
- $1

Если понятно, то отлично и молодец, если нет, то необходимо изучить, т.к. необходимо знать код, который используешь :)

2020-03-25 17:00 UTC, chexex commented on src/reducers/getMessage.js
> +  //GET_MESSAGE_FAILURE,
почему?

2020-03-25 17:00 UTC, chexex commented on src/reducers/sendMessage.js
> +  //SEND_MESSAGE_FAILURE,
Либо удалить совсем, либо раскомментировать, либо подписать доп комменты, типа 
`TODO: раскомментить в следующей дз`

2020-03-25 19:28 UTC, Minrael commented on src/actions/getMessage.js
> +  //GET_MESSAGE_FAILURE,
Потому что линтер ругается на неиспользумые переменные, из-за этого не собиралс проект в тревисе. В перспективе планирую дописать, поэтому не удаляю совсем, чтобы не забыть.

2020-03-25 19:29 UTC, Minrael commented on src/components/MessageList.js
> +                let withEmoji = msg.replace(/&#(\w+)#&/g, ' <i class="$1 emoji"></i> ');
Да, иначе бы выполнение дз не занимало несколько недель)

2020-03-25 19:30 UTC, Minrael commented on src/reducers/sendMessage.js
> +  //SEND_MESSAGE_FAILURE,
ок

2020-04-05 09:09 UTC, martinkomitsky approved these changes
давай разберемся с твоим случаем на стороне тревиса позже.
как вижу, в этом PR несколько домашек. Напоминаю, что каждую дз надо делать в отдельной ветке

дз 1: 6
дз 3: 12

2020-04-05 09:09 UTC, merged