Home work2
Minrael/2020-1-Track-Frontend-M-Kerechanina pull request #2
Opened 2020-04-06 22:23 UTC by Minrael

# Домашнее задание №2

Прошу @martinkomitsky, @chexex или @priver проверить его.

Что было сделано:
* Добавлены E2E тесты: 
1. Переход по ссылкам на страницу чата
2. Отправка текстового сообщения 
3. Отправка сообщения со смайлом

* Временно роутинг происходит через переменную process.env.PUBLIC_URL, т.к. вариант с относительными ссылками не работает

2020-04-10 21:03 UTC, martinkomitsky requested changes
пригласи  @chexex , пожалуйста, в репозиторий

2020-04-11 19:23 UTC, chexex submitted a review, later dismissed
Все хорошо, только для будущих e2e учти мой комментарий :)

6 баллов

2020-04-11 19:23 UTC, chexex commented on .travis.yml
> +  - "sh -e /etc/init.d/xvfb start"
интересный набор настроек :)

2020-04-11 19:23 UTC, chexex commented on endtoend/chat.test.js
> +        await page.click(`a[name="chatsLink"]`);
Желательно после клика и перехода на страницу, проверить, что на странице есть нужный элемент/текст/картинка

2020-04-11 21:40 UTC, Minrael commented on .travis.yml
> +  - "sh -e /etc/init.d/xvfb start"
Настройки отсюда: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md

Я не очень понимаю почему, но это помогло решить проблему с тестами в CI

2020-04-15 07:29 UTC, martinkomitsky approved these changes

2020-04-15 07:30 UTC, martinkomitsky approved these changes

2020-04-15 07:30 UTC, martinkomitsky commented
@Minrael, Смержил. Не забудь спуллить из мастера правки в свою основную ветку

2020-04-15 07:30 UTC, merged